package com.example.founderdetailsapp;

import android.os.Bundle;
import android.view.View;
import android.widget.GridLayout;
import android.widget.Toast;

import androidx.activity.EdgeToEdge;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;
import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import java.util.ArrayList;
import java.util.List;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        EdgeToEdge.enable(this);
        setContentView(R.layout.activity_main);

        RecyclerView recyclerView = findViewById(R.id.recycler_view);
        List<Item> itemList = new ArrayList<>();
        itemList.add(new Item(R.mipmap.google_ceo, "Google",
                "Sundar Pichai is the CEO of Google and its parent company Alphabet. He was born on June 10, 1972, in Madurai, Tamil Nadu, India. His full name is Pichai Sundararajan. Sundar grew up in a middle-class family where his father worked as an electrical engineer and his mother was a stenographer. From childhood, Sundar had a sharp memory and an interest in technology. He was especially good at remembering telephone numbers and solving problems in a logical way.\n\n" +
                        "He completed his early education in Chennai and later studied Metallurgical Engineering at the Indian Institute of Technology (IIT) Kharagpur. After graduating, Sundar received a scholarship to study in the United States. He earned a Master’s degree in Material Sciences and Engineering from Stanford University and then completed an MBA from the Wharton School at the University of Pennsylvania. These achievements gave him a strong foundation in both technology and business.\n\n" +
                        "In 2004, Sundar Pichai joined Google. At first, he worked on the Google Toolbar, a feature that made it easier for people to search on Google. Later, he became the driving force behind the creation of Google Chrome, which went on to become the world’s most widely used web browser. His ability to lead big projects with calmness and intelligence made him stand out within the company. He later managed products like Gmail, Google Maps, and Android.\n\n" +
                        "In 2015, Sundar Pichai was appointed CEO of Google, and in 2019, he became CEO of Alphabet as well. Under his leadership, Google has focused on artificial intelligence, cloud services, and sustainable growth. Sundar is admired globally for his humility, simple lifestyle, and focus on innovation. His journey from a small town in India to becoming the head of one of the biggest technology companies in the world inspires millions of students and professionals. His story teaches us that with hard work, education, and determination, one can achieve success at the highest level."));
        itemList.add(new Item(R.mipmap.reliance_ceo, "Reliance",
                "Mukesh Ambani is the Chairman and Managing Director of Reliance Industries Limited (RIL), one of India’s largest and most valuable companies. Born on April 19, 1957, Mukesh is the son of Dhirubhai Ambani, the legendary founder of Reliance. He studied Chemical Engineering at the Institute of Chemical Technology (ICT), Mumbai, and later pursued an MBA at Stanford University, though he left midway to join his father in expanding Reliance.\n\n" +
                        "Under Mukesh Ambani’s leadership, Reliance has grown from a textile and polyester business into a global conglomerate with interests in petrochemicals, refining, oil & gas exploration, retail, telecommunications, and digital services. He became the head of Reliance after his father’s death in 2002 and has since transformed the company into a modern powerhouse.\n\n" +
                        "One of his biggest achievements has been the launch of Reliance Jio in 2016, which disrupted the Indian telecom market by offering affordable 4G data and free calls. Jio quickly became the largest telecom operator in India, bringing millions of Indians online and revolutionizing the digital economy. This move not only strengthened Reliance’s position but also made India one of the world’s biggest consumers of mobile internet.\n\n" +
                        "Reliance Retail, another arm of the company, is India’s largest retail business, offering everything from groceries to electronics. Under Mukesh Ambani, Reliance Retail has partnered with global companies like Facebook and Google to integrate technology into shopping and payments. His vision has always been about combining energy, technology, and retail to create a self-reliant and digitally empowered India.\n\n" +
                        "Mukesh Ambani is also among the world’s richest businessmen, regularly appearing in the Forbes list of global billionaires. Despite his global stature, he continues to focus on India’s growth, investing heavily in green energy, digital infrastructure, and job creation. He has announced plans for Reliance to move towards renewable energy like solar and hydrogen, showing his forward-thinking approach for the future.\n\n" +
                        "Through innovation, bold investments, and strategic partnerships, Mukesh Ambani has transformed Reliance into a global giant. His leadership reflects ambition, discipline, and a strong belief in India’s potential, making him one of the most influential business leaders in the world today."));
        itemList.add(new Item(R.mipmap.infosys_ceo, "Infosys",
                "Salil Parekh is the Chief Executive Officer and Managing Director of Infosys, one of India’s largest IT services and consulting companies. He took over as CEO in January 2018, bringing with him over 30 years of global experience in the technology and consulting industry. Born in 1964 in India, Salil completed his Aeronautical Engineering degree from the Indian Institute of Technology (IIT), Bombay. Later, he pursued a Master’s degree in Computer Science and Mechanical Engineering from Cornell University in the United States.\n\n" +
                        "Before joining Infosys, Salil worked at Capgemini, a global consulting and technology services company, where he held senior leadership roles for more than 25 years. At Capgemini, he managed global businesses across financial services, cloud, infrastructure, and application outsourcing. His strong background in consulting and IT solutions made him an ideal leader for Infosys at a time when the company was looking for stability and global expansion.\n\n" +
                        "Since becoming CEO, Salil Parekh has focused on strengthening Infosys’s digital transformation capabilities, artificial intelligence, cloud computing, and automation services. Under his leadership, Infosys has secured major global clients in banking, healthcare, retail, and manufacturing sectors. He has also worked on expanding Infosys’s presence in the U.S., Europe, and Asia-Pacific regions, ensuring the company remains competitive against global IT giants.\n\n" +
                        "One of his significant contributions has been promoting employee-friendly policies and reskilling initiatives. He strongly believes that in the era of AI and automation, continuous learning is the key to long-term success. Infosys, under his leadership, has invested in training programs, digital platforms, and sustainability projects.\n\n" +
                        "Salil Parekh is known for his calm and steady leadership style. Unlike many high-profile CEOs, he prefers to stay away from controversies and instead focuses on delivering consistent results. His ability to handle global clients, adapt to new technologies, and lead large teams has helped Infosys maintain its reputation as a trusted IT services provider worldwide.\n\n" +
                        "With his vision, Infosys continues to grow as a digital-first company that helps businesses worldwide embrace innovation, sustainability, and future-ready technology solutions."));

        itemList.add(new Item(R.mipmap.microsoft_ceo, "Microsoft",
                "Satya Nadella is the Chief Executive Officer (CEO) of Microsoft, one of the largest technology companies in the world. He was born on August 19, 1967, in Hyderabad, India. Nadella grew up in a simple family and always had a deep interest in learning and exploring technology. His father was an Indian Administrative Service officer, and his mother was a Sanskrit lecturer. From his school days, Nadella was curious about computers and science, which later shaped his career path.\n\n" +
                        "He studied Electrical Engineering at Manipal Institute of Technology in India. After completing his degree, Satya went to the United States for higher studies. He earned a Master’s degree in Computer Science from the University of Wisconsin–Milwaukee. Later, he also completed an MBA from the University of Chicago Booth School of Business. This combination of technical and business knowledge gave him a strong background to work in the technology industry.\n\n" +
                        "In 1992, Satya Nadella joined Microsoft. In the beginning, he worked on developing Windows NT, an operating system designed for business users. Over the years, he played key roles in Microsoft’s cloud computing division, including the launch and growth of Microsoft Azure. His leadership helped Microsoft transform from a company focused only on software like Windows and Office into a global leader in cloud technology and artificial intelligence.\n\n" +
                        "In February 2014, Satya Nadella became the CEO of Microsoft, replacing Steve Ballmer. Under his leadership, Microsoft regained its position as one of the most valuable companies in the world. Nadella emphasized cloud computing, AI, and collaboration tools such as Microsoft Teams and Office 365. He also promoted a culture of innovation, learning, and inclusivity inside the company.\n\n" +
                        "Satya Nadella is known not just for his technical vision but also for his calm and humble personality. He wrote a book titled 'Hit Refresh,' where he shared his journey, leadership lessons, and Microsoft’s future vision. His success story is an inspiration to millions of people, especially Indians, showing that with hard work, education, and determination, it is possible to lead one of the biggest companies in the world."));
        itemList.add(new Item(R.mipmap.nvidia_ceo, "Nvidia",
                "Jensen Huang is the co-founder, President, and Chief Executive Officer (CEO) of Nvidia, a global leader in graphics processing units (GPUs) and artificial intelligence technologies. He was born on February 17, 1963, in Tainan, Taiwan. At the age of nine, he moved to the United States with his family. As a young boy, he faced many challenges adapting to a new country, but his interest in learning and technology kept growing. He later earned a degree in Electrical Engineering from Oregon State University and a Master’s degree in Electrical Engineering from Stanford University.\n\n" +
                        "In 1993, Jensen Huang co-founded Nvidia along with Chris Malachowsky and Curtis Priem. At that time, computer graphics were still in their early stages, and few believed that GPUs would have a massive role in the future. However, Jensen had a clear vision that graphics processing would not only change gaming but also transform industries like design, data centers, and artificial intelligence. His leadership and determination helped Nvidia grow from a small startup into a company worth hundreds of billions of dollars.\n\n" +
                        "One of Jensen’s biggest contributions was leading Nvidia into artificial intelligence and deep learning. Nvidia’s GPUs became the foundation for AI research, powering self-driving cars, robotics, healthcare, and advanced data analysis. Under his leadership, Nvidia also became a pioneer in high-performance computing and cloud-based GPU technology. Today, almost every AI model, including ChatGPT, is powered by Nvidia’s GPUs.\n\n" +
                        "Jensen Huang is widely respected for his unique leadership style. He is known for his energy, vision, and willingness to take risks. Unlike many CEOs who focus only on business growth, Jensen also focuses on building a culture of innovation and creativity. He often appears at Nvidia’s conferences wearing his iconic leather jacket, which has become a symbol of his personality.\n\n" +
                        "Throughout his career, Jensen Huang has received many awards, including being named one of the world’s top CEOs by Harvard Business Review. His journey from Taiwan to Silicon Valley and his success in building one of the most important companies in the world is an inspiration to millions of entrepreneurs and students. Jensen’s story shows that with vision, courage, and hard work, it is possible to change the world through technology."));
        itemList.add(new Item(R.mipmap.amazon_ceo, "Amazon",
                "Andy Jassy is the Chief Executive Officer (CEO) of Amazon, one of the world’s largest e-commerce and technology companies. He was born on January 13, 1968, in Scarsdale, New York, United States. From his early years, Andy was known for being focused, disciplined, and hardworking. He completed his undergraduate degree from Harvard College and later earned an MBA from Harvard Business School, which gave him a strong foundation in leadership and management.\n\n" +
                        "Andy Jassy joined Amazon in 1997, just a few years after the company was founded by Jeff Bezos. At that time, Amazon was mainly an online bookstore, but Jassy quickly became an important part of the company’s growth. He worked closely with Jeff Bezos on many projects and eventually became the head of Amazon Web Services (AWS), the company’s cloud computing division. Under his leadership, AWS became the backbone of the internet, serving millions of businesses, governments, and startups around the world. Today, AWS is one of the most profitable divisions of Amazon.\n\n" +
                        "In February 2021, Andy Jassy officially replaced Jeff Bezos as the CEO of Amazon. Taking over such a massive company was not an easy task, but Jassy’s years of experience and proven leadership in AWS made him the perfect choice. As CEO, he has focused on improving Amazon’s technology, expanding cloud services, and maintaining Amazon’s dominance in e-commerce. He also emphasizes employee welfare and sustainability, working to make Amazon a more responsible global company.\n\n" +
                        "Andy Jassy is known for his strong decision-making, calm personality, and deep knowledge of technology. He believes in long-term innovation and is always looking for ways to improve services for customers. He often says that companies should keep reinventing themselves to stay successful. His journey from joining Amazon as a young leader to becoming its CEO is a story of dedication, patience, and consistent performance.\n\n" +
                        "Today, Andy Jassy is considered one of the most influential CEOs in the technology industry. His leadership shows how vision, innovation, and persistence can help a person grow from managing one division to running one of the world’s largest companies."));
        itemList.add(new Item(R.mipmap.samsung_ceo, "Samsung",
                "Samsung Electronics, one of the biggest technology companies in the world, is led by two co-CEOs: Han Jong-hee and Kyung Kye-hyun. Their leadership represents the strength of teamwork and specialization, as both handle different divisions within the company. Together, they are guiding Samsung to maintain its position as a global leader in smartphones, semiconductors, displays, and consumer electronics.\n\n" +
                        "Han Jong-hee is the Vice Chairman and CEO of Samsung Electronics. He is mainly responsible for the DX (Device eXperience) division, which includes smartphones, TVs, home appliances, and display products. Han has worked at Samsung for many years and has built a strong reputation as a product expert, especially in displays and visual products. Under his leadership, Samsung’s Galaxy smartphones and QLED TVs have achieved massive global success. Han believes in creating user-friendly, innovative, and stylish products that connect people worldwide.\n\n" +
                        "On the other hand, Kyung Kye-hyun is the CEO in charge of Samsung’s Device Solutions (DS) division, which focuses on semiconductors and memory chips. He is a highly skilled engineer and leader who has been with Samsung for decades. Kyung is leading Samsung’s mission to remain the number one memory chip manufacturer in the world, while also expanding into advanced semiconductor technologies such as logic chips and processors. His work is crucial because semiconductors are the backbone of modern technology, powering everything from smartphones to supercomputers.\n\n" +
                        "Both Han and Kyung were appointed as co-CEOs in December 2021. This dual leadership structure was designed to strengthen Samsung’s overall growth by combining expertise in both consumer products and advanced technology. Together, they balance creativity, engineering, and business strategy to drive Samsung forward.\n\n" +
                        "Under their leadership, Samsung has continued to invest in research and development, artificial intelligence, 5G technology, and sustainable solutions. The company is also focusing on eco-friendly products, digital health, and smart home innovation. Han Jong-hee and Kyung Kye-hyun are known for their commitment to teamwork, innovation, and global leadership.\n\n" +
                        "The story of Samsung’s co-CEOs shows that modern businesses can succeed through shared leadership, where different talents and expertise come together to achieve common goals. Their vision ensures that Samsung remains not only a technology giant but also a company that inspires trust and progress around the world."));
        itemList.add(new Item(R.mipmap.facebook_ceo, "Meta (Facebook)",
                "Mark Zuckerberg is the co-founder, chairman, and Chief Executive Officer (CEO) of Meta Platforms, previously known as Facebook. He was born on May 14, 1984, in White Plains, New York, USA. From an early age, Mark showed great interest in computers and programming. His father taught him Atari BASIC programming, and by the time he was in middle school, he was already creating computer programs. Later, he attended Phillips Exeter Academy, where he continued to sharpen his skills in coding and software development.\n\n" +
                        "Mark Zuckerberg went to Harvard University in 2002. During his second year, he created a website called 'Thefacebook' along with his roommates Eduardo Saverin, Andrew McCollum, Dustin Moskovitz, and Chris Hughes. The site was originally made for Harvard students to connect online, but it quickly spread to other universities and eventually to the entire world. In 2004, Zuckerberg officially launched Facebook, which became one of the fastest-growing social networks in history.\n\n" +
                        "Under Mark’s leadership, Facebook expanded its features, introducing the News Feed, Messenger, Groups, and Pages. He also oversaw the acquisitions of Instagram, WhatsApp, and Oculus, making Meta a giant in social media, communication, and virtual reality. In 2021, Facebook rebranded itself as Meta, with a new focus on building the 'metaverse,' a digital world where people can interact in 3D environments using virtual and augmented reality.\n\n" +
                        "Mark Zuckerberg is known for his determination, vision, and risk-taking attitude. Despite many challenges, including legal battles, privacy concerns, and criticisms about social media’s impact on society, he has continued to lead the company with long-term goals. His leadership has transformed Meta into one of the world’s most powerful technology companies, connecting billions of people worldwide.\n\n" +
                        "Outside of business, Mark and his wife Priscilla Chan created the Chan Zuckerberg Initiative, which supports education, healthcare, and scientific research. He is also recognized for his philanthropic efforts, promising to donate most of his wealth to charitable causes.\n\n" +
                        "Mark Zuckerberg’s journey from a college student working in his dorm room to becoming one of the world’s most influential CEOs is a remarkable story of innovation, persistence, and vision. His work continues to shape the way people communicate, share, and connect across the globe."));
        itemList.add(new Item(R.mipmap.apple_ceo, "Apple",
                "Tim Cook is the Chief Executive Officer (CEO) of Apple Inc., one of the most valuable technology companies in the world. He was born on November 1, 1960, in Robertsdale, Alabama, USA. Cook grew up in a modest family where his father worked in a shipyard and his mother was a homemaker. From an early age, Tim was known for being disciplined, hardworking, and focused on academics. He later studied Industrial Engineering at Auburn University and went on to earn an MBA from Duke University’s Fuqua School of Business.\n\n" +
                        "Before joining Apple, Tim Cook worked at companies like IBM, Compaq, and Intelligent Electronics. At IBM, he gained valuable experience in supply chain management and business operations. These skills later played an important role in his success at Apple. In 1998, Steve Jobs, the co-founder of Apple, personally invited Tim Cook to join the company. At that time, Apple was struggling, but Cook believed in Jobs’s vision and decided to take the risk.\n\n" +
                        "Tim Cook initially served as Senior Vice President of Worldwide Operations at Apple. He became known for streamlining Apple’s supply chain, reducing costs, and making the company more efficient. His operational expertise helped Apple become more profitable and reliable. Over the years, Cook rose through the ranks and became the Chief Operating Officer (COO) of the company.\n\n" +
                        "In August 2011, following the resignation of Steve Jobs due to health issues, Tim Cook was appointed CEO of Apple. Many people wondered if he would be able to fill Jobs’s shoes, but Cook proved himself as a capable leader. Under his leadership, Apple has launched many successful products, including new generations of the iPhone, Apple Watch, iPad, and MacBook. He also expanded Apple’s focus on services like Apple Music, Apple TV+, and iCloud, which became major sources of revenue.\n\n" +
                        "Tim Cook is admired for his calm leadership style, focus on teamwork, and commitment to social responsibility. He is the first openly gay CEO of a Fortune 500 company, and he has been vocal about issues such as privacy, equality, renewable energy, and sustainability. Under his guidance, Apple became the first U.S. company to reach a market value of over $1 trillion.\n\n" +
                        "Tim Cook’s journey shows that leadership is not just about innovation but also about discipline, values, and vision. His story continues to inspire professionals around the world who want to lead with integrity and purpose."));
        itemList.add(new Item(R.mipmap.swiggy_ceo, "Swiggy",
                "Sriharsha Majety is the co-founder and Chief Executive Officer (CEO) of Swiggy, one of India’s largest food delivery and online services platforms. He was born in 1986 in Andhra Pradesh, India, and grew up in a family that valued education and discipline. From his early years, Sriharsha was curious, hardworking, and passionate about building new ideas. He pursued his Bachelor’s degree in Electrical and Electronics Engineering from BITS Pilani, one of India’s top institutes. Later, he completed his MBA from the Indian Institute of Management (IIM) Calcutta, which gave him strong business and leadership skills.\n\n" +
                        "Before starting Swiggy, Sriharsha worked in consulting and also gained international exposure by working in financial services in London. However, his entrepreneurial spirit pushed him to return to India and create something of his own. In 2013, along with Nandan Reddy, he launched a logistics company called Bundl. Although Bundl did not succeed as expected, the experience taught them valuable lessons about business and customer needs. Soon after, in 2014, Sriharsha Majety, Nandan Reddy, and Rahul Jaimini co-founded Swiggy in Bengaluru.\n\n" +
                        "Swiggy started with a simple mission: to make food delivery fast, reliable, and convenient. At a time when food delivery in India was unorganized and often slow, Swiggy built its own delivery fleet to ensure quality service. Under Sriharsha’s leadership, Swiggy grew rapidly across India and became a household name. Today, Swiggy operates in hundreds of cities and has millions of customers who rely on it daily.\n\n" +
                        "Over the years, Swiggy has expanded beyond food delivery. It now offers services like Swiggy Instamart for groceries, Swiggy Genie for pick-up and drop services, and cloud kitchens to support restaurants. Sriharsha’s vision is to make Swiggy a platform that solves everyday convenience problems for people, not just food delivery. His ability to adapt, innovate, and focus on customer satisfaction has been key to Swiggy’s success.\n\n" +
                        "Sriharsha Majety is admired for his resilience and problem-solving attitude. He believes that failures are stepping stones to success and encourages young entrepreneurs to keep experimenting and learning. His journey from a student with big dreams to the CEO of one of India’s leading startups is an inspiration for today’s youth. He proves that with passion, persistence, and courage, anyone can build something that impacts millions of lives."));
        itemList.add(new Item(R.mipmap.tcs_ceo, "TCS",
                "K. Krithivasan is the Chief Executive Officer (CEO) and Managing Director of Tata Consultancy Services (TCS), one of the world’s largest IT services and consulting companies. He took charge in June 2023 after the retirement of former CEO Rajesh Gopinathan. Krithivasan is a veteran at TCS with more than 30 years of experience in the company, making him a respected leader within the Tata Group. His deep understanding of technology, clients, and global business has positioned him as the right person to lead TCS into the future.\n\n" +
                        "Krithivasan completed his Bachelor’s degree in Mechanical Engineering from the University of Madras. Later, he pursued a Master’s degree in Industrial and Management Engineering from the Indian Institute of Technology (IIT) Kanpur. His educational background gave him a strong mix of technical and managerial expertise, which helped him grow within the IT industry.\n\n" +
                        "He joined TCS in 1989, at a time when the IT services industry in India was still in its early stages. Over the decades, Krithivasan worked in various leadership roles across industries such as banking, financial services, and insurance (BFSI). He became known for his ability to build long-term client relationships, deliver complex technology projects, and drive large-scale digital transformation. Before becoming CEO, he was the Global Head of the BFSI division at TCS, which is the company’s largest business unit.\n\n" +
                        "As CEO, Krithivasan focuses on strengthening TCS’s position in digital services, cloud computing, artificial intelligence, and consulting. He is also committed to expanding TCS’s global footprint, with offices and delivery centers in more than 50 countries. Under his leadership, TCS continues to help businesses worldwide adopt new technologies, improve efficiency, and stay competitive in a rapidly changing market.\n\n" +
                        "Krithivasan is admired for his humble personality, strategic thinking, and people-first leadership style. Colleagues describe him as approachable and supportive, someone who encourages teamwork and innovation. His appointment as CEO reflects TCS’s tradition of promoting leaders from within, ensuring stability and continuity.\n\n" +
                        "His journey from a young engineer in Chennai to the CEO of one of the world’s most valuable IT companies is an inspiration for many. K. Krithivasan’s story proves that dedication, continuous learning, and loyalty to one’s organization can lead to the highest levels of success."));
        itemList.add(new Item(R.mipmap.zomato_ceo, "Zomato",
                "Deepinder Goyal is the co-founder and CEO of Zomato, one of India’s most popular food delivery and restaurant discovery platforms. He started Zomato in 2008 along with Pankaj Chaddah, initially as a small website called Foodiebay, which helped people discover restaurant menus online. Over the years, it evolved into Zomato and grew rapidly to become a global company that connects millions of customers with restaurants and food delivery partners every day.\n\n" +
                        "Deepinder Goyal was born in Muktsar, Punjab, in 1983. He completed his schooling in Punjab and later pursued a degree in Mathematics and Computing from the prestigious Indian Institute of Technology (IIT) Delhi. During his time at IIT, he showed strong analytical and problem-solving skills. After graduation, he worked as a consultant at Bain & Company in New Delhi, where he noticed that employees often struggled to find restaurant menus. This observation sparked the idea that eventually became Zomato.\n\n" +
                        "From its early beginnings, Zomato expanded quickly across major Indian cities and later to international markets like the UAE, Australia, and the UK. Under Deepinder’s leadership, the company transitioned from being just a restaurant discovery app to a full-fledged food delivery and technology company. Zomato also introduced services like online table reservations, Zomato Pro for premium membership benefits, and cloud kitchens.\n\n" +
                        "In July 2021, Zomato made history by becoming one of the first major Indian tech startups to go public with a successful IPO (Initial Public Offering). The listing was a landmark moment for India’s startup ecosystem and boosted confidence in tech companies. Deepinder Goyal played a key role in steering the company through challenges like competition from Swiggy, rising operational costs, and the impact of the COVID-19 pandemic.\n\n" +
                        "Known for his resilience and innovative thinking, Goyal often shares his thoughts on startups and leadership through social media. He believes in building long-term sustainable businesses and has focused on improving unit economics and profitability at Zomato. His leadership style combines vision, adaptability, and a strong focus on execution.\n\n" +
                        "Deepinder Goyal’s journey from a small-town boy in Punjab to the CEO of a billion-dollar company is inspiring for young entrepreneurs. His story reflects how determination, innovative ideas, and persistence can turn a simple problem into a global business solution."));
        itemList.add(new Item(R.mipmap.wipro_ceo, "Wipro",
                "Thierry Delaporte is the Chief Executive Officer (CEO) and Managing Director of Wipro Limited, one of India’s largest IT services and consulting companies. He took over the role in July 2020, becoming the first non-Indian CEO in Wipro’s history. With more than 25 years of global leadership experience, Thierry has played a key role in transforming Wipro into a stronger, more competitive player in the IT industry.\n\n" +
                        "Thierry Delaporte was born in France and completed his studies in Economics and Finance at Sciences Po (Institut d’Études Politiques de Paris), a highly reputed institution. Before joining Wipro, he worked at Capgemini for over two decades. At Capgemini, he held several leadership positions including Chief Operating Officer (COO) and a member of the Group Executive Board. His experience there gave him expertise in driving business growth, client relations, and large-scale digital transformation.\n\n" +
                        "When Thierry joined Wipro in 2020, the company was facing stiff competition from rivals like TCS, Infosys, and Accenture. His leadership came at a crucial time during the COVID-19 pandemic, which reshaped the IT services landscape globally. Thierry brought a fresh perspective and a global outlook, focusing on simplifying the organization, strengthening client relationships, and accelerating Wipro’s shift towards digital, cloud, and cybersecurity services.\n\n" +
                        "Under his leadership, Wipro launched a new operating model designed to make the company more agile and customer-centric. He emphasized growth in key sectors such as digital transformation, cloud solutions, engineering services, and consulting. Thierry also prioritized building stronger partnerships with global technology companies and expanding Wipro’s footprint in international markets like the United States and Europe.\n\n" +
                        "Thierry Delaporte is known for his disciplined and structured leadership style. He believes in empowering teams, maintaining a strong focus on execution, and delivering value to clients. His goal is to position Wipro as a top-tier IT services provider on the global stage. Since he became CEO, Wipro has reported steady growth in revenue and has secured several large deals with international clients.\n\n" +
                        "Beyond business, Thierry is also passionate about corporate responsibility and sustainability. He encourages initiatives that focus on digital inclusion, education, and environmental sustainability. His vision for Wipro is not just about financial growth but also about making a positive impact on society.\n\n" +
                        "Thierry Delaporte’s journey from a French business leader to the CEO of an Indian IT giant reflects the global nature of today’s technology industry. His leadership continues to inspire employees and demonstrates how cross-cultural collaboration can drive innovation and success."));
        itemList.add(new Item(R.mipmap.oyo_ceo, "OYO",
                "Ritesh Agarwal is the founder and CEO of OYO Rooms, one of the world’s largest hospitality and budget hotel networks. He was born in 1993 in Bissam Cuttack, Odisha, India. Coming from a small town, Ritesh had big dreams and a passion for entrepreneurship from a very young age. At just 17 years old, he moved to Delhi to pursue his ambitions, where he started working on travel and hotel-related ideas.\n\n" +
                        "Initially, he launched a platform called Oravel Stays in 2012, which aimed to provide affordable accommodation options. However, he quickly realized that India’s hospitality industry needed standardization in budget hotels. This idea led him to create OYO Rooms in 2013, focusing on offering clean, comfortable, and affordable hotel rooms with consistent standards. His vision was simple: to make quality living spaces accessible to everyone at a reasonable price.\n\n" +
                        "Ritesh Agarwal’s hard work and innovative thinking paid off. In 2013, he became the first Indian to receive the Thiel Fellowship, a prestigious program started by PayPal co-founder Peter Thiel. The fellowship provided him with funding and mentorship, which helped him grow OYO rapidly. Within a few years, OYO expanded across India and later into international markets, including China, Southeast Asia, Europe, and the United States.\n\n" +
                        "Under Ritesh’s leadership, OYO transformed from a small startup into a global hospitality giant. It partnered with thousands of hotels and offered technology-driven solutions for booking, pricing, and customer experience. OYO also expanded into vacation homes and co-working spaces. Despite challenges such as the COVID-19 pandemic, which severely impacted the travel and hotel industry, Ritesh worked on restructuring the company and focusing on sustainable growth.\n\n" +
                        "Ritesh Agarwal is known for his determination, problem-solving skills, and ability to take risks. His journey from a small-town boy to the CEO of a billion-dollar company is a source of inspiration for young entrepreneurs worldwide. He believes in the power of technology and innovation to solve real-world problems and create opportunities.\n\n" +
                        "Today, OYO continues to be one of the leading names in budget hospitality. Ritesh Agarwal’s story reflects how vision, hard work, and resilience can turn an idea into a global success. His leadership is shaping the future of affordable travel and hospitality for millions of people across the world."));
        itemList.add(new Item(R.mipmap.flipkart_ceo, "Flipkart",
                "Kalyan Krishnamurthy is the CEO of Flipkart, one of India’s largest e-commerce companies. Flipkart was founded in 2007 by Sachin Bansal and Binny Bansal, and it quickly grew into a household name for online shopping in India. Kalyan Krishnamurthy, who became CEO in 2017, has played a major role in taking Flipkart to new heights in the highly competitive e-commerce market.\n\n" +
                        "Kalyan Krishnamurthy studied finance and business management, and before joining Flipkart, he worked with companies like eBay and Tiger Global, which is one of Flipkart’s key investors. His strong background in finance and global business strategy helped him bring a professional, structured approach to Flipkart’s operations. Initially, he joined Flipkart as the Head of Category Design Organization in 2013, where he worked on improving the product categories and customer experience. After proving his capability, he was appointed as the CEO in 2017.\n\n" +
                        "Under his leadership, Flipkart has continued to expand in fashion, electronics, grocery, and furniture. One of his biggest achievements was leading Flipkart during Walmart’s acquisition in 2018, when Walmart bought a majority stake in Flipkart for $16 billion. This was one of the biggest deals in the global e-commerce industry and gave Flipkart the financial strength to compete strongly with Amazon in India.\n\n" +
                        "Kalyan Krishnamurthy has focused on building Flipkart as a customer-first company. He has emphasized fast delivery, quality assurance, digital payments, and building trust among Indian consumers. He also supported innovation through Flipkart’s technology teams, improving the app’s interface, AI-driven recommendations, and supply chain efficiency.\n\n" +
                        "Even during challenges like heavy competition from Amazon and new players like Reliance’s JioMart, Kalyan’s strategy has kept Flipkart among the top choices for online shopping in India. Flipkart also owns fashion e-commerce brands like Myntra and Jabong, and has investments in PhonePe, a popular digital payments platform.\n\n" +
                        "Today, Flipkart continues to be a market leader in India, serving millions of customers every day. Kalyan Krishnamurthy’s vision, financial discipline, and focus on innovation have made him one of the most respected business leaders in the Indian startup ecosystem. His journey shows how strong leadership and strategic thinking can transform a company into a long-term success."));


        MyAdapter myAdapter = new MyAdapter(this,itemList);
        GridLayoutManager layoutManager = new GridLayoutManager(this,2);
        recyclerView.setLayoutManager(layoutManager);
        recyclerView.setAdapter(myAdapter);





        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main), (v, insets) -> {
            Insets systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars());
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom);
            return insets;
        });
    }
}